// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1EEnzUAlNn0K8McXTHhTQTX6CqYtPjro',
    appId: '1:141638815415:web:99bffc96a1cdb11b328732',
    messagingSenderId: '141638815415',
    projectId: 'fir-connect-f48e7',
    authDomain: 'fir-connect-f48e7.firebaseapp.com',
    storageBucket: 'fir-connect-f48e7.appspot.com',
    measurementId: 'G-61FNQD3QR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3XEjGX9Mj-ECxaXu1FC4sMGsLd9s1RrE',
    appId: '1:141638815415:android:95c020fd78fb305d328732',
    messagingSenderId: '141638815415',
    projectId: 'fir-connect-f48e7',
    storageBucket: 'fir-connect-f48e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDN-anhzJ2TCt04mngJNombnIMOsKlbNY',
    appId: '1:141638815415:ios:d317fdc10f36b2c8328732',
    messagingSenderId: '141638815415',
    projectId: 'fir-connect-f48e7',
    storageBucket: 'fir-connect-f48e7.appspot.com',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDN-anhzJ2TCt04mngJNombnIMOsKlbNY',
    appId: '1:141638815415:ios:379e2f1842b95479328732',
    messagingSenderId: '141638815415',
    projectId: 'fir-connect-f48e7',
    storageBucket: 'fir-connect-f48e7.appspot.com',
    iosBundleId: 'com.example.finalApp.RunnerTests',
  );
}
